### ISSUE TITLE
Automatically set out parameter if not included

### ISSUE THREAD

**Issue by Anagmate** [olmokramer/atom-coffee-autocompile#2]
If "out" parameter is not included in file, use fileNameWithoutExtension.js - often, I don't want to spend my time specifying the path for saving the file

**Comment by olmokramer** [comment]
Thanks for the feedback. I like this idea. I added it behind a setting because I don't want every coffee script file to be compiled automatically. It's included in the new version 0.3.0. Please let me know what you think
