### ISSUE TITLE
Filename placeholders 

### ISSUE THREAD

**Issue by jerone** [olmokramer/atom-coffee-autocompile#6]
Atom packages [sass-autocompile](https://github.com/armin-pfaeffle/sass-autocompile) and [jade-autocompile](https://github.com/ManRueda/jade-autocompile) has a [nice](https://github.com/armin-pfaeffle/sass-autocompile#filename-pattern-for-expanded-compiled-files) [feature](https://github.com/ManRueda/jade-autocompile#configuration) where you can use `$1` and `$2` as placeholder for the original basename respectively the file extension.

**Comment by olmokramer** [comment]
@jerone That's really useful, thanks for the suggestion! I've implemented it on the `master` branch of this repository, and I'll publish a new version on APM in a few minutes.

**Comment by jerone** [comment]
Confirmed implemented. Thanks!

**Comment by jerone** [comment]
_Ps. If you add "fixed #6" or "closed #6" in your commit messages, Github will immediately close corresponding issues as soon as they are implemented._

**Comment by olmokramer** [comment]
Thanks, I knew GitHub did that, but I keep forgetting to do that :)
