### ISSUE TITLE
SourceMap is broken

### ISSUE THREAD

**Issue by jerone** [olmokramer/atom-coffee-autocompile#7]
It appears that sourcemap support is broken. Both the `file` and `sources` properties are empty.

```coffeescript
# out: test.js, sourcemap: true
i = 0
```

Sourcemap output:
```json
{
  "version": 3,
  "file": "",
  "sourceRoot": "",
  "sources": [
    ""
  ],
  "names": [],
  "mappings": "AAEA;AAAA,MAAA;;EAAA,CAAA,GAAI;AAAJ"
}
```

**Comment by olmokramer** [comment]
Hello Jeroen, thank you for the report. I think I've fixed this issue on the main branch, could you please verify that?

**Comment by jerone** [comment]
Just tried your code and getting an error:

```
coffee-script:
Error: Cannot find module 'coffee-script' from 'C:\Users\jerone\Desktop\test'
```

_It's been an while since I used coffeescript out of Atom_

**Comment by olmokramer** [comment]
Thanks for letting me know. I added a feature that tries to load a local coffee-script installation from the path of the `.coffee` file, but it seems that it failed when no local copy was available. New version should fix that.

**Comment by jerone** [comment]
Thanks for fixing.

I can confirm that the sourcemap is created now.
It how however doesn't show relative paths with above code example:

```json
{
  "version": 3,
  "file": "C:\\Users\\jerone\\Desktop\\test\\test.js",
  "sourceRoot": "",
  "sources": [
    "C:\\Users\\jerone\\Desktop\\test\\test.coffee"
  ],
  "names": [],
  "mappings": "AACA;AAAA,MAAA;;EAAA,CAAA,GAAI;AAAJ"
}
```

**Comment by olmokramer** [comment]
Ok, there was an issue where it used the full absolute path when a file didn't belong to any of the open project folders. I also forgot to take Windows path separators into account. That should be fixed on the master branch. Unfortunately I do not have a machine running Windows, so I can't really test if everything works over there.

**Comment by jerone** [comment]
> Unfortunately I do not have a machine running Windows, so I can't really test if everything works over there.

Just tested the latest code and this is the output:

```json
{
  "version": 3,
  "file": "C:\\Users\\jerone\\Desktop\\test\\test.coffee.js",
  "sourceRoot": "",
  "sources": [
    "test.coffee"
  ],
  "names": [],
  "mappings": "AACA;AAAA,MAAA;;EAAA,CAAA,GAAI;AAAJ"
}
```

Only thing left is the `file` changing to a relative path.

**Comment by olmokramer** [comment]
Ok, everything should work now. For some reason I was trying to set the `"file"` entry to a path relative to the current project. I've changed it so it will just take the filename.

**Comment by jerone** [comment]
Looks good :+1: :shipit:

**Comment by olmokramer** [comment]
Alright! v0.6.2 released :fireworks: Thanks for the help Jeroen!
